name: Build and deploy ASP.Net Core app to Azure Web App - BookStoreApp

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Publish
        run: dotnet publish ./BookStore.Api/BookStore.Api.csproj -c Release -o ./publish

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: net-app
          path: ./publish

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: net-app
          path: ./publish

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_03DA2E868BBA4180AB1D8EEE5D1E5C90 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E665BD84DEB846C495C3B722332D9FA4 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C718C757446A4CE592C89CE2F15B23E6 }}

      - name: Install dotnet-ef
        run: dotnet tool install --global dotnet-ef --version 8.0.0

      - name: Apply EF Core migrations
        run: |
          dotnet ef database update \
            --project "./BookStore.Data/BookStore.Data.csproj" \
            --startup-project "./BookStore.Api/BookStore.Api.csproj" \
            --connection "$DB_CONNECTION_STRING"
        env:
          DB_CONNECTION_STRING: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'BookStoreApp'
          slot-name: 'Production'
          package: ./publish
